version: "3.8"

services:
  # Redis Cache Service
  redis:
    image: redis:7.2-alpine
    container_name: ticketsystem-redis
    ports:
      - "6379:6379"
    restart: unless-stopped
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Your Backend Service
  ticketsystem-backend:
    build: .
    container_name: ticketsystem-backend
    ports:
      - "8080:8080"
    depends_on:
      - redis
      - kafka
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://host.docker.internal:5432/ticketsystem
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: sachinholla
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      JWT_SECRET: mysecretkey12345678901234567890
      APP_MAIL_FROM: sachinholla01@gmail.com
      APP_FILE_BASE_URL: http://localhost:8080
      SPRING_MAIL_HOST: smtp.gmail.com
      SPRING_MAIL_PORT: 587
      SPRING_MAIL_USERNAME: sachinholla01@gmail.com
      SPRING_MAIL_PASSWORD: tjuf hend fuun gole
      SPRING_MAIL_PROTOCOL: smtp
      SPRING_MAIL_PROPERTIES_MAIL_SMTP_AUTH: "true"
      SPRING_MAIL_PROPERTIES_MAIL_SMTP_STARTTLS_ENABLE: "true"
      SPRING_SERVLET_MULTIPART_MAX_FILE_SIZE: 20MB
      SPRING_SERVLET_MULTIPART_MAX_REQUEST_SIZE: 20MB
      SPRING_WEB_RESOURCES_STATIC_LOCATIONS: file:./uploads/
      # Redis Configuration
      SPRING_DATA_REDIS_HOST: redis
      SPRING_DATA_REDIS_PORT: 6379
      SPRING_CACHE_TYPE: redis
      # Kafka Configuration
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    volumes:
      - ./uploads:/app/uploads
    restart: unless-stopped

  # Zookeeper (needed for Kafka)
  zookeeper:
    image: bitnami/zookeeper:latest
    ports:
      - "2181:2181"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  # Kafka
  kafka:
    image: bitnami/kafka:latest
    ports:
      - "9092:9092"
      - "29092:29092" 
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092,PLAINTEXT_HOST://localhost:29092
      - KAFKA_CFG_LISTENERS=PLAINTEXT://0.0.0.0:9092,PLAINTEXT_HOST://0.0.0.0:29092
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT

      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper
# Define volumes
volumes:
  redis_data:
    driver: local
